SELECT 
  YEAR(sale_dt) as time_unit,
  br_cd,
  br_nm,
  biz_cd,
  biz_nm,
  sale_gb,
  sub_br_cd,
  sub_br_nm,
  season_nm,
  season_cd,
  season_seq,
  year_cd,
  year_nm,
  it,
  it_nm,
  it_gb,
  it_gb_nm,
  item,
  item_nm,
  onoff_flag,
  is_flex,
  sales_type,
  first_lv_class,
  second_lv_class,
  SUM(sales_price) / 1000000 as rev
FROM agabang_dw.daily_shop_sales_by_dimension
WHERE date_format(sale_dt, '%m-%d') >= date_format(DATE '{{ dateRange.value.start || moment().startOf("year").format("YYYY-MM-DD") }}', '%m-%d') AND date_format(sale_dt, '%m-%d') <= date_format(DATE '{{ dateRange.value.end || moment().subtract(1, "days").format("YYYY-MM-DD") }}', '%m-%d')
  AND YEAR(sale_dt) >= {{ moment().subtract('years',2).year() }}
AND biz_cd IN ('{{ bizMultiSelect.value.join("','") }}') 
AND br_cd IN ('{{ brandMultiSelect.value.join("','") }}')
GROUP BY
  YEAR(sale_dt),
  br_cd,
  br_nm,
  biz_cd,
  biz_nm,
  sale_gb,
  sales_type,
  first_lv_class,
  second_lv_class,
  sub_br_cd,
  sub_br_nm,
  it,
  it_nm,
  it_gb,
  it_gb_nm,
  item,
  item_nm,
  onoff_flag,
  is_flex,
  season_nm,
  season_cd,
  season_seq,
  year_cd,
  year_nm